### PR TITLE
Support nested options

### PR DESCRIPTION
**Pull request by sttk**
This function will be used in vinyl-fs to solve the issue [gulp#2288]( https://github.com/gulpjs/gulp/issues/2288).

### CODE REVIEW

**Comment by phated** [comment]
Unfortunately this won't solve the sourcemap issue. I will try to follow up on that when I have some free time.

**Comment by sttk** [comment]
@phated This pr only enables to specify advanced sourcemap options.
Moreover, we need to modify vinyl-fs and vinyl-sourcemap to write outputs by these options in source map files.

```
gulp.src('src/**/*.js', {sourcemaps: true})
  .pipe(gulp.dest('dist', {
    sourcemaps: { destPath: '.',  sourceRoot: '../src' }  // Enable to specify nested options like this.
  })); 
```

At [https://github.com/gulpjs/vinyl-fs/blob/master/lib/dest/sourcemap.js#L11](https://github.com/gulpjs/vinyl-fs/blob/master/lib/dest/sourcemap.js#L11), these nested options can be gotten like following.

```
var srcMap = optResolver.resolve('sourcemaps', file);  // => { destPath: '.',  sourceRoot: '../src'  }

**Comment by 3cp** [comment]
Just a thought, no matter how is it fixed underneath, in this surface API:

```js
gulp.dest('dist', {
    sourcemaps: { destPath: '.',  sourceRoot: '../src' }
  });
```

The sourceRoot is unnecessary, because you can automatically figure out sourceRoot based on the first arg to `gulp.dest` which is `'dist'`, plus the original `file.base` in vinyl-fs file itself.

I would suggest gulp to get the sourceRoot right by default for both `gulp.dest('dist', {sourcemaps: true})` and `gulp.dest('dist', {sourcemaps: '.'})`.

**Comment by phated** [comment]
I think if we are supporting nested options, we are complicating our options too much. Gulp was never intended to have the complete set of gulp-sourcemaps; it is only the initialization. End-users are expected to combine other plugins for advanced features.

**Comment by phated** [comment]
@sttk I created a new tool for updating the repository scaffold. I'll need to show you that some time.

**Pull request closed without merging**
